list: $/yamobile/staff/models/member/columns.yaml
modelClass: Yamobile\Staff\Models\Member
title: Members
noRecordsMessage: "backend::lang.list.no_records"
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
  buttons: list_toolbar
  search:
    prompt: "backend::lang.list.search_prompt"
recordUrl: "yamobile/staff/members/update/:id"
