list: $/yamobile/staff/models/position/columns.yaml
modelClass: Yamobile\Staff\Models\Position
title: Positions
noRecordsMessage: "backend::lang.list.no_records"
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
  buttons: list_toolbar
  search:
    prompt: "backend::lang.list.search_prompt"
recordUrl: "yamobile/staff/positions/update/:id"
